-- Branchpoint publication intelligence schema
create extension if not exists pgcrypto;

create table if not exists public.publications (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  kind text not null check (kind in ('publication','book','newsletter','site','course','other')),
  canonical_url text,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_items (
  id uuid primary key default gen_random_uuid(),
  publication_id uuid not null references public.publications(id) on delete cascade,
  slug text not null,
  title text not null,
  content_type text not null check (content_type in ('article','note','social_post','video','book','chapter','course','other')),
  canonical_url text,
  topic text,
  perspective text,
  status text not null default 'published',
  published_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (publication_id, slug)
);

create table if not exists public.content_distribution (
  id uuid primary key default gen_random_uuid(),
  content_item_id uuid not null references public.content_items(id) on delete cascade,
  platform text not null,
  platform_post_id text,
  url text,
  format text,
  creative_variant text,
  cta_variant text,
  published_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.metric_snapshots (
  id bigint generated by default as identity primary key,
  publication_id uuid not null references public.publications(id) on delete cascade,
  content_item_id uuid references public.content_items(id) on delete set null,
  distribution_id uuid references public.content_distribution(id) on delete set null,
  platform text not null,
  captured_at timestamptz not null default now(),
  followers integer,
  subscribers integer,
  views integer,
  impressions integer,
  likes integer,
  comments integer,
  shares integer,
  saves integer,
  clicks integer,
  conversions integer,
  revenue_cents integer,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.experiments (
  id uuid primary key default gen_random_uuid(),
  content_item_id uuid references public.content_items(id) on delete cascade,
  name text not null,
  hypothesis text,
  variable text,
  variant text,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.outcomes (
  id uuid primary key default gen_random_uuid(),
  publication_id uuid not null references public.publications(id) on delete cascade,
  content_item_id uuid references public.content_items(id) on delete set null,
  distribution_id uuid references public.content_distribution(id) on delete set null,
  outcome_type text not null,
  value numeric not null,
  unit text,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists metric_snapshots_publication_time_idx
  on public.metric_snapshots (publication_id, captured_at desc);
create index if not exists metric_snapshots_content_time_idx
  on public.metric_snapshots (content_item_id, captured_at desc);
create index if not exists content_distribution_platform_idx
  on public.content_distribution (platform, published_at desc);
create index if not exists outcomes_publication_time_idx
  on public.outcomes (publication_id, occurred_at desc);

alter table public.publications enable row level security;
alter table public.content_items enable row level security;
alter table public.content_distribution enable row level security;
alter table public.metric_snapshots enable row level security;
alter table public.experiments enable row level security;
alter table public.outcomes enable row level security;

-- No anon/authenticated policies are created intentionally.
-- The Vercel API route uses a Supabase server-side secret key.

insert into public.publications (slug, title, kind, canonical_url, status)
values
  ('branchpoint', 'Branchpoint', 'publication', 'https://branchpoint.space', 'active'),
  ('architecting-intelligence', 'Architecting Intelligence', 'book', null, 'active'),
  ('zdx-binary-academy', 'ZeroDriveX Binary Academy', 'site', 'https://binary.zdxai.us', 'active')
on conflict (slug) do update set
  title = excluded.title,
  kind = excluded.kind,
  canonical_url = coalesce(excluded.canonical_url, public.publications.canonical_url),
  status = excluded.status,
  updated_at = now();

insert into public.content_items (
  publication_id, slug, title, content_type, topic, perspective, status, published_at
)
select
  p.id,
  'indias-rocket-launch-wasnt-the-story',
  'India’s Rocket Launch Wasn’t the Story',
  'article',
  'Space · India · Global capability',
  'The launch makes accumulated technological capability more visible than the headline alone.',
  'published',
  now()
from public.publications p
where p.slug = 'branchpoint'
on conflict (publication_id, slug) do update set
  title = excluded.title,
  topic = excluded.topic,
  perspective = excluded.perspective,
  status = excluded.status,
  published_at = coalesce(public.content_items.published_at, excluded.published_at),
  updated_at = now();

insert into public.metric_snapshots (
  publication_id, content_item_id, platform, followers, metadata
)
select
  p.id,
  c.id,
  'substack',
  1,
  jsonb_build_object('baseline', true, 'note', 'First recorded Branchpoint follower baseline')
from public.publications p
join public.content_items c on c.publication_id = p.id
where p.slug = 'branchpoint'
  and c.slug = 'indias-rocket-launch-wasnt-the-story'
  and not exists (
    select 1 from public.metric_snapshots m
    where m.publication_id = p.id
      and m.platform = 'substack'
      and (m.metadata ->> 'baseline') = 'true'
  );


insert into public.content_items (
  publication_id, slug, title, content_type, canonical_url, topic, perspective, status, published_at, metadata
)
select
  p.id,
  'understanding-apple-mach-o-binary-internals',
  'Understanding Apple Mach-O Binary Internals',
  'course',
  'https://binary.zdxai.us',
  'Binary analysis · Apple Mach-O · Software internals',
  'Technical course product tracked alongside publications and books for acquisition attribution.',
  'published',
  now(),
  jsonb_build_object('price_cents', 4999, 'currency', 'USD')
from public.publications p
where p.slug = 'zdx-binary-academy'
on conflict (publication_id, slug) do update set
  title = excluded.title,
  content_type = excluded.content_type,
  canonical_url = excluded.canonical_url,
  topic = excluded.topic,
  perspective = excluded.perspective,
  status = excluded.status,
  metadata = excluded.metadata,
  updated_at = now();

update public.publications
set metadata = jsonb_build_object(
  'lifetime_pass_cents', 7999,
  'currency', 'USD',
  'lifetime_pass_note', 'Lifetime access to current and future courses'
),
updated_at = now()
where slug = 'zdx-binary-academy';
